name: Build and Deploy in Development(BackEnd)

on:
  push:
    branches: [main]

jobs:
  Acabot:
    uses: ./.github/workflows/ecs.yml
    with:
      AWSDefaultRegion: us-east-1
      EnvironmentName: Test
      SmallCaseEnvironment: test
      ProjectName: Immigo
      parameters: "EnvironmentName=Test ProjectName=Immigo PrimaryRegion=us-east-1"
    secrets: inherit
